delivery-service:
  git-commit-id:
    id-abbrev: '@git.commit.id.abbrev@'
    author: '@git.commit.user.name@'
    message: '@git.commit.message.full@'
    branch: '@git.branch@'
  loader:
    server-url: 'http://localhost:8080/'
    directory-path: 'C:/Hot-load/'
    cron-expression: '0 * * * * ?'
    threads: 6
    load-config:
      - directory-name: 'categories/'
        controller-url: 'v1/categories'
      - directory-name: 'products/'
        controller-url: 'v1/products'
    enabled: true
spring:
  datasource:
    url: jdbc:sqlserver://localhost\SQLEXPRESS;database=testDb
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: test
    password: 1111
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:configs/liquibase/changelog-master.xml
    enabled: true
  h2:
    console:
      enabled: true