git-info:
  id-abbrev: '@git.commit.id.abbrev@'
  author: '@git.commit.user.name@'
  message: '@git.commit.message.full@'
  branch: '@git.branch@'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  liquibase:
    change-log: classpath:configs/liquibase/changelog-master.xml
    enabled: true
  h2:
    console:
      enabled: true