git-info:
  id-abbrev: '@git.commit.id.abbrev@'
  author: '@git.commit.user.name@'
  message: '@git.commit.message.full@'
  branch: '@git.branch@'

spring:
  datasource:
    url: jdbc:sqlserver://localhost\SQLEXPRESS;database=testDb
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: test
    password: 1111
  jpa:
    showSql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  liquibase:
    change-log: classpath:configs/liquibase/changelog-master.xml
    enabled: true
  h2:
    console:
      enabled: true